openapi: "3.0.1"
info:
  version: 0.1.0
  title: OfTest

servers:
  - url: https://pretend.api

paths:
  /alpha
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
              - $ref: '#/definitions/schemas/alpha'

paths:
  /beta
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
              - $ref: '#/definitions/schemas/beta'

paths:
  /alphabeta
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
              - $ref: '#/definitions/schemas/alphabeta'

definitions:
  schemas:
    alpha: {
      "type": "object",
      "properties": {
        "value" : {
          "type" : "integer"
        }
      }
    }

    beta: {
      "type": "object",
      "properties": {
        "value" : {
          "type" : "string"
        }
      }
    }

    alphabeta: 
      type: object
      anyOf:
        - $ref: '#/definitions/schemas/alpha'
        - $ref: '#/definitions/schemas/beta'
